spring.application.name=stockflow
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost/cafeteria}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jackson.time-zone=America/Sao_Paulo
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
springdoc.swagger-ui.path=/swagger-ui.html
