spring.application.name=stockflow
spring.datasource.url=jdbc:postgresql://localhost:5432/stockflow
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.expiracao = 120
spring.secret ="yfgew7gf37wduifg980938"
spring.emissor="vitor"